# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondScreen(object):
    def setupUi(self, SecondScreen):
        SecondScreen.setObjectName("SecondScreen")
        SecondScreen.resize(1022, 761)
        self.centralwidget = QtWidgets.QWidget(SecondScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 0, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.btn_left_down = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left_down.setGeometry(QtCore.QRect(10, 680, 101, 31))
        font = QtGui.QFont()
        font.setFamily("ヒラギノ角ゴ ProN W6")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_left_down.setFont(font)
        self.btn_left_down.setObjectName("btn_left_down")
        self.btn_right_down = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right_down.setGeometry(QtCore.QRect(920, 700, 101, 31))
        font = QtGui.QFont()
        font.setFamily("ヒラギノ角ゴ ProN W6")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_right_down.setFont(font)
        self.btn_right_down.setObjectName("btn_right_down")
        self.btn_left_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left_up.setGeometry(QtCore.QRect(0, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("ヒラギノ角ゴ ProN W6")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_left_up.setFont(font)
        self.btn_left_up.setObjectName("btn_left_up")
        self.btn_right_up = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right_up.setGeometry(QtCore.QRect(930, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("ヒラギノ角ゴ ProN W6")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_right_up.setFont(font)
        self.btn_right_up.setObjectName("btn_right_up")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(-10, 0, 1041, 731))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView.raise_()
        self.pushButton.raise_()
        self.label.raise_()
        self.btn_left_down.raise_()
        self.btn_right_down.raise_()
        self.btn_left_up.raise_()
        self.btn_right_up.raise_()
        SecondScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SecondScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 18))
        self.menubar.setObjectName("menubar")
        SecondScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SecondScreen)
        self.statusbar.setObjectName("statusbar")
        SecondScreen.setStatusBar(self.statusbar)

        self.retranslateUi(SecondScreen)
        QtCore.QMetaObject.connectSlotsByName(SecondScreen)

    def retranslateUi(self, SecondScreen):
        _translate = QtCore.QCoreApplication.translate
        SecondScreen.setWindowTitle(_translate("SecondScreen", "MainWindow"))
        self.pushButton.setText(_translate("SecondScreen", "戻る"))
        self.label.setText(_translate("SecondScreen", "キャリブレーション"))
        self.btn_left_down.setText(_translate("SecondScreen", "左下"))
        self.btn_right_down.setText(_translate("SecondScreen", "右下"))
        self.btn_left_up.setText(_translate("SecondScreen", "左上"))
        self.btn_right_up.setText(_translate("SecondScreen", "右上"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondScreen = QtWidgets.QMainWindow()
    ui = Ui_SecondScreen()
    ui.setupUi(SecondScreen)
    SecondScreen.show()
    sys.exit(app.exec_())
